#define VER_FILEDESCRIPTION_STR "Berkeley DB Engine"
#define VER_PRODUCTNAME_STR VER_FILEDESCRIPTION_STR
#define VER_INTERNALNAME_STR "BerkeleyDB"
#define VER_ORIGINALFILENAME_STR "bdb.dll"
#define VER_PRODUCTVERSION 5,3,21,0
#define VER_PRODUCTVERSION_STR "5.3.21"
