#define VER_FILEDESCRIPTION_STR "Tor library"
#define VER_PRODUCTNAME_STR VER_FILEDESCRIPTION_STR
#define VER_INTERNALNAME_STR "tor"
#define VER_ORIGINALFILENAME_STR "tor.dll"
#define VER_PRODUCTVERSION 2,6,3,0
#define VER_PRODUCTVERSION_STR "2.6.3-alpha"

#ifdef _AFXDLL
#	define _USRDLL
#endif




