#define VER_FILEDESCRIPTION_STR "OpenSSL Crypto library"
#define VER_PRODUCTNAME_STR VER_FILEDESCRIPTION_STR
#define VER_INTERNALNAME_STR "openssl"
#define VER_ORIGINALFILENAME_STR "openssl.dll"
#define VER_PRODUCTVERSION 1,1,2,0
#define VER_PRODUCTVERSION_STR "1.1.2"

#ifdef _DLL
#	define _AFXDLL
#	define _USRDLL
#endif
