#define VER_FILEDESCRIPTION_STR "MPIR library"
#define VER_PRODUCTNAME_STR VER_FILEDESCRIPTION_STR
#define VER_INTERNALNAME_STR "mpir"
#define VER_ORIGINALFILENAME_STR "mpir.dll"
#define VER_PRODUCTVERSION 2,6,0,0
#define VER_PRODUCTVERSION_STR "2.6.0"

#define _USRDLL
