#define VER_FILEDESCRIPTION_STR "SQLite Database Engine"
#define VER_PRODUCTNAME_STR VER_FILEDESCRIPTION_STR
#define VER_INTERNALNAME_STR "SQLite3"
#define VER_ORIGINALFILENAME_STR "sqlite3.dll"
#define VER_PRODUCTVERSION 3,8,7,0
#define VER_PRODUCTVERSION_STR "3.8.7"

#define _USRDLL
